baseurl: 'https://lipk.org'
languageCode: zh-cn
title: 未命名的站点名称
enableEmoji: true
disableRSS: false
disableKinds:
  - taxonomy
  - term
publishDir: dist
permalinks:
  blog: '/blog/:year/:month/:day/:slug/'
menu:
  main:
    - name: 返回
      url: /
      weight: 1
    - name: 博客
      url: /blog/
      weight: 2
    - name: 菜谱
      url: /food/
      weight: 3
    - name: 关于
      url: /about/
      weight: 4
  about:
    - name: 返回
      url: /
      weight: 1
    - name: 博客
      url: /blog/
      weight: 2
    - name: 菜谱
      url: /food/
      weight: 3
    - name: 关于
      url: /about/
      weight: 4
  resume:
    - name: 返回
      url: /
      weight: 1
    - name: 博客
      url: /blog/
      weight: 2
    - name: 菜谱
      url: /food/
      weight: 3
    - name: 关于
      url: /about/
      weight: 4
  blog:
    - name: 返回
      url: /
      weight: 1
    - name: 博客
      url: /blog/
      weight: 2
    - name: 菜谱
      url: /food/
      weight: 3
    - name: 关于
      url: /about/
      weight: 4
  food:
    - name: 返回
      url: /
      weight: 1
    - name: 博客
      url: /blog/
      weight: 2
    - name: 菜谱
      url: /food/
      weight: 3
    - name: 关于
      url: /about/
      weight: 4
params:
  description: lipk.org; Personal website of Pengkun Lee;
  since: '2018'
  slogan: 这里是一个口号
  title: 标题名称
  author: 作者名称
  githubContentURL: 'http://github.com/zsdycs/lipk.org/edit/master/content/'
  edit: 编辑
  license: 版权
author:
  blog: 作者名称
markup:
  defaultMarkdownHandler: goldmark
  blackFriday:
    angledQuotes: false
    footnoteAnchorPrefix: ''
    footnoteReturnLinkContents: ↩
    fractions: true
    hrefTargetBlank: false
    latexDashes: true
    nofollowLinks: false
    noreferrerLinks: false
    plainIDAnchors: true
    skipHTML: false
    smartDashes: true
    smartypants: true
    smartypantsQuotesNBSP: false
    taskLists: true
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      autoHeadingID: true
      autoHeadingIDType: github
      attribute:
        block: false
        title: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ''
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    startLevel: 1
    endLevel: 3
    ordered: false
